server.port: 8081

solon:
  app:
    name: 'etl-job-simple'
    group: 'cn.easydat'
  serialization:
    json:
      dateAsFormat: 'yyyy-MM-dd HH:mm:ss' #配置日期格式（默认输出为时间戳）
      dateAsTimeZone: 'GMT+8' #配置时区
      dateAsTicks: false #将date转为毫秒数（和 dateAsFormat 二选一）
      longAsString: true #将long型转为字符串输出 （默认为false）
      boolAsInt: false   #将bool型转为字符串输出 （默认为false）
      nullStringAsEmpty: false
      nullBoolAsFalse: false
      nullNumberAsZero: false
      nullArrayAsEmpty: false
      nullAsWriteable: false #输出所有null值
      enumAsName: false #枚举使用名字（v2.2.1 后支持）
  config.load:
    - "app.env.yml"

solon.logging.appender:
  console:
    level: INFO
    enable: true #是否启用
    pattern: "%d{yyyyMMdd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %logger{1.3.*} - [%method,%line] - %msg%n"
  file:
    name: "logs/${solon.app.name}"
    rolling: "logs/${solon.app.name}_%d{yyyy-MM-dd}_%i.log"
    level: INFO
    enable: true #是否启用
    pattern: "%d{yyyyMMdd HH:mm:ss.SSS} [%thread] %-5level %logger{1.3.*} - [%method,%line] - %msg%n"
    extension: ".log"   #v2.2.18 后支持（例：.log, .log.gz, .log.zip）
    maxFileSize: "10 MB"
    maxHistory: "7"
    
solon.logging.logger:
  "root":  #默认记录器配置
    level: TRACE
  "com.zaxxer.hikari":
    level: WARN

